-- ID와 자식의 수를 출력
WITH RESULT AS (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT E.ID, 
CASE 
    WHEN(R.CHILD_COUNT IS NULL) THEN 0
    ELSE R.CHILD_COUNT
END AS CHILD_COUNT
    FROM ECOLI_DATA E
LEFT JOIN RESULT R
ON E.ID = R.PARENT_ID
;