-- 코드를 작성해주세요
WITH LEN AS (
    SELECT ID,
    CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
    END LENGTH
    FROM FISH_INFO
)

SELECT ROUND(AVG(LENGTH),2) AS AVERAGE_LENGTH
    FROM LEN;

