SELECT b.WRITER_ID, u.nickname, sum(price) as TOTAL_SALES from USED_GOODS_BOARD as b
JOIN USED_GOODS_USER AS u ON u.USER_ID = b.WRITER_ID
WHERE STATUS = 'DONE' GROUP BY WRITER_ID HAVING sum(price) >= 700000
ORDER BY SUM(PRICE);