-- 코드를 입력하세요
SELECT 
C.HISTORY_ID,
C.CAR_ID,
DATE_FORMAT(C.START_DATE, '%Y-%m-%d') AS START_DATE,
DATE_FORMAT(C.END_DATE, '%Y-%m-%d') AS END_DATE,
CASE 
    WHEN DATEDIFF(C.END_DATE, C.START_DATE) >= 29 THEN '장기 대여'
    ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE START_DATE LIKE '2022-09%'
ORDER BY C.HISTORY_ID DESC
;
