SELECT FISH_COUNT, FISH_NAME
FROM (
    SELECT FISH_TYPE, count(*) FISH_COUNT
      FROM FISH_INFO
      GROUP BY FISH_TYPE
) C 
left join FISH_NAME_INFO N
ON N.FISH_TYPE = C.FISH_TYPE
ORDER BY FISH_COUNT desc